### PR TITLE
Upgrade TypeScript to 6.0.3

### LINKED ISSUE #335: Upgrade TypeScript from 5.x to 6.0.3
## Summary

The workspace currently uses TypeScript 5.5.2 at the root and 5.9.3 in several packages. TypeScript 5 is superseded and outside Microsoft's stated servicing line, while TypeScript 6 still receives limited security and high-severity fixes. Upgrading to 6.0.3 also provides stricter import validation, better generic type inference, modern ES2025/DOM types, more predictable ambient type loading, and a supported migration path toward TypeScript 7.

Initial checks show that the main SDK packages compile successfully with TypeScript 6.0.3, but this is not a version-only update.

## Required changes

- Align all direct TypeScript dependencies on `6.0.3`.
- Add explicit Node types to the React Native bindings plugin configuration.
- Replace deprecated `moduleResolution: "Node"` with `"Bundler"` in the Vite TypeScript configurations.
- Add an appropriate declaration for the Next.js CSS side-effect import.
- Update TypeScript-coupled tooling whose current peer ranges exclude TypeScript 6, including `rollup-plugin-dts` and `@typescript-eslint`.
- Regenerate the pnpm lockfile under the repository's supported Node 22 and pnpm 11.12.0 environment.

## Acceptance criteria

- `pnpm typecheck`, `pnpm build`, `pnpm build:reactnative`, `pnpm docs:build`, and the existing test workflows pass.
- The clean install has no unsupported TypeScript peer dependencies.
- Generated declaration files and published package contents contain no unintended changes.
- TypeScript 6 deprecations are resolved rather than hidden with `ignoreDeprecations`.

References: 
* [TypeScript support policy](https://github.com/microsoft/TypeScript/blob/main/SUPPORT.md) 
* [TypeScript 6.0 release notes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-6-0.html)
* [TypeScript 6 servicing policy](https://devblogs.microsoft.com/typescript/progress-on-typescript-7-december-2025/)

### PR DESCRIPTION
**Pull request by Juwon-Ogunseye**
Closes #335

## Summary

Aligns all direct TypeScript dependencies on `6.0.3` and resolves the resulting deprecations and breakages properly (no `ignoreDeprecations`).

## Changes

- Bumped `typescript` to `6.0.3` in the root and all 11 packages/examples that declare it directly.
- Added explicit Node types to the React Native bindings plugin `tsconfig.json` (`"types": ["node"]`), plus an explicit `rootDir` — TypeScript 6 no longer infers this automatically.
- Replaced deprecated `moduleResolution: "Node"` with `"Bundler"` in the two Vite-based `tsconfig.json` files (`create-fedimint-app`'s Vite template, `examples/vite-core`).
- Added an explicit `rootDir` to `packages/react/tsconfig.build.json` for the same TS6 inference-strictness reason as above.
- Added `examples/next-js/css.d.ts` declaring the `*.css` module shape, so the Next.js example's CSS side-effect import type-checks under TS6.
- Bumped `rollup-plugin-dts` to `^6.4.1` in `packages/core` and `packages/transport-web` (resolved to `6.5.1` in the lockfile — the previous version's peer range excluded TS6). No direct `@typescript-eslint` dependency exists in this repo; it only appears transitively.
- Fixed `docs/.vitepress/config.ts`'s Twoslash transformer: it was calling `transformerTwoslash()` with no arguments, which fell back to internal TS5-era defaults (`baseUrl`, mismatched `module`/`moduleResolution`) that TS6 now flags. Passed explicit, correct `compilerOptions` (`moduleResolution: Bundler`, `module: ESNext`, `baseUrl: undefined` to override the library's own hardcoded default).
- Regenerated `pnpm-lock.yaml` under Node 22 / pnpm 11.12.0.

## Bonus fix found along the way

`rollup-plugin-dts@6.4.1`'s stricter dts bundling surfaced a real latent bug: `LogLevel` (used publicly in `WalletDirector.setLogLevel`) was never re-exported from `packages/core/src/index.ts`, so consumers couldn't actually import the type by name (would've hit `TS2742` downstream). Added the missing export.

## Verification

- ✅ `pnpm typecheck` — passes
- ✅ `pnpm build` — passes
- ✅ `pnpm docs:build` — passes (269s, every Twoslash-checked doc snippet type-checks clean)
- ⚠️ `pnpm build:reactnative` — fails with `Cannot find module './generated/fedimint_client_uniffi'`. **Confirmed pre-existing and unrelated to this PR** via `git stash` against the original `main` — same failure occurs with TypeScript 5.5.2. Appears to require a uniffi codegen step not present in a fresh clone.
- Also found and confirmed pre-existing (via the same `git stash` method, unrelated to this PR): `examples/next-js` fails to build independently of this change — `new FedimintWallet()` argument mismatch against the current `@fedimint/core` API.
- No unsupported TypeScript peer dependencies were introduced by this PR; remaining peer warnings (`@expo/require-utils`, `unbuild`, transitive `rollup-plugin-dts@6.3.0`) are pre-existing transitive dependencies outside this repo's direct control.
- `ignoreDeprecations` was not used anywhere — all TS6 deprecations were resolved at the root cause.

### CODE REVIEW

**Review by MrImmortal09 — APPROVED** [review]
Thanks for the PR @Juwon-Ogunseye
